server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#spring:
#  application:
#    name: gateway-server
#  cloud:
#    gateway:
#      routes:
#        - id: first-service
##          uri: http://localhost:55534/
#
#          # ?????(???? ???? ???? ???? ???)?? ??, ??? ? ??(uri)
#          uri: lb://MY-FIRST-SERVICE
#
#          # ??? ?????? ?? ??? '/first-service/**? ???? ~' ?? ??
#          predicates:
#            - Path=/first-service/**
#
#          # Global, Custom ?? ??? ???? ??
#          # (request ? response header? ? ??, segment? ??? ?? ??)
#          filters:
#            - AddRequestHeader=first-request, first-request-header
#            - AddResponseHeader=first-response, first-response-header
#            - RewritePath=/first-service/(?<segment>.*), /$\{segment}
#        - id: second-service
##          uri: http://localhost:55540/
#          uri: lb://MY-SECOND-SERVICE
#          predicates:
#            - Path=/second-service/**
#          filters:
#            - AddRequestHeader=second-request, second-request-header
#            - AddResponseHeader=second-response, second-response-header
#            - RewritePath=/second-service/(?<segment>.*), /$\{segment}
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://SWCAMP-USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<segment>.*), /$\{segment}
